services:
  - type: web
    name: conciliador-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    

    startCommand: "gunicorn conciliador_web.wsgi:application"